#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 14 21:31:35 2021

@author: hagen
"""
from recreationdotgov import campgrounds, recreationlab
import sys 
import traceback

try:
    checkin = '05/21/2021'
    number_of_nights = 2
    out = campgrounds.co_great_sand_dunes.make_query(checkin, number_of_nights, 
                                    notify='email',
                                    log = True,
                                    keep_looking=False)
    
    checkin = '06/04/2021'
    number_of_nights = 2
    out = campgrounds.co_great_sand_dunes.make_query(checkin, number_of_nights, 
                                    notify='email',
                                    log = True,
                                    keep_looking=False)
except:
    error, error_txt, trace = sys.exc_info()
    tm = ['{}: {}'.format(error.__name__, error_txt.args[0])] + traceback.format_tb(trace)
    txt = '\n'.join(tm)
    recreationlab.notify_by_mail('Failed recreation.gov run', txt)