#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 14 21:31:35 2021

@author: hagen
"""
from recreationdotgov import campgrounds, recreationlab
import sys 
import traceback

try:    
    checkin = '08/07/2021'
    out = campgrounds.co.make_query(checkin, 1, 
                                    notify='email',
                                    log = True,
                                    keep_looking=False)
except:
    error, error_txt, trace = sys.exc_info()
    tm = ['{}: {}'.format(error.__name__, error_txt.args[0])] + traceback.format_tb(trace)
    txt = '\n'.join(tm)
    recreationlab.notify_by_mail('Failed recreation.gov run', txt)